# Generated by Django 5.2.17 on 2026-09-26 02:10

import django.db.models.deletion
import sensibilisation.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CasPratique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lettre', models.CharField(max_length=2)),
                ('metier', models.CharField(max_length=80)),
                ('situation', models.TextField()),
                ('reponse', models.TextField(verbose_name='Réponse attendue')),
            ],
            options={
                'verbose_name': 'cas pratique',
                'ordering': ['lettre'],
            },
        ),
        migrations.CreateModel(
            name='EmailExercice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('expediteur_nom', models.CharField(max_length=150)),
                ('expediteur_adresse', models.CharField(max_length=200)),
                ('objet', models.CharField(max_length=250)),
                ('corps', models.TextField()),
                ('piege', models.BooleanField(default=True, verbose_name='Piégé ?')),
                ('indices', models.TextField(help_text='Un indice par ligne')),
            ],
            options={
                'verbose_name': "email d'exercice",
                'verbose_name_plural': "emails d'exercice",
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='EtapeScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('heure', models.CharField(max_length=20)),
                ('evenement', models.TextField()),
                ('bonne_reaction', models.TextField()),
            ],
            options={
                'verbose_name': 'étape du scénario',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('numero', models.CharField(blank=True, help_text='Ex. : Module 1 (vide pour ouverture/clôture)', max_length=20, verbose_name='Numéro affiché')),
                ('titre', models.CharField(max_length=200)),
                ('horaire', models.CharField(blank=True, max_length=20)),
                ('duree_minutes', models.PositiveIntegerField(default=30)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, verbose_name="Nom de l'entreprise")),
                ('secteur', models.CharField(blank=True, help_text='Ex. : banque, assurance, industrie', max_length=100, verbose_name='Secteur')),
                ('domaine_email', models.CharField(blank=True, help_text='Ex. : bci-banque.sn', max_length=100, verbose_name='Domaine email')),
                ('contact_it', models.CharField(blank=True, max_length=100, verbose_name='Contact informatique (numéro interne)')),
                ('adresse_signalement', models.CharField(blank=True, max_length=150, verbose_name='Adresse pour signaler un email suspect')),
                ('contact_client', models.CharField(blank=True, max_length=200, verbose_name='Contact client (nom, email)')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'organisation cliente',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('texte', models.TextField()),
                ('explication', models.TextField(blank=True, verbose_name='Message à faire passer')),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Choix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lettre', models.CharField(max_length=2)),
                ('texte', models.CharField(max_length=300)),
                ('correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choix', to='sensibilisation.question')),
            ],
            options={
                'verbose_name_plural': 'choix',
                'ordering': ['lettre'],
            },
        ),
        migrations.CreateModel(
            name='Seance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('groupe', models.CharField(blank=True, help_text='Ex. : Groupe A', max_length=50)),
                ('lieu', models.CharField(blank=True, max_length=150)),
                ('formateur', models.CharField(max_length=150)),
                ('participants_prevus', models.PositiveIntegerField(default=30)),
                ('presents', models.PositiveIntegerField(blank=True, null=True)),
                ('code', models.CharField(default=sensibilisation.models.generer_code, editable=False, max_length=8, unique=True)),
                ('quiz_entree_ouvert', models.BooleanField(default=False)),
                ('quiz_sortie_ouvert', models.BooleanField(default=False)),
                ('evaluation_ouverte', models.BooleanField(default=False)),
                ('notes_formateur', models.TextField(blank=True, verbose_name='Questions et remarques de la salle')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('slide_index', models.PositiveIntegerField(default=0)),
                ('atelier_ouvert', models.BooleanField(default=False)),
                ('scenario_ouvert', models.BooleanField(default=False)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seances', to='sensibilisation.organisation')),
            ],
            options={
                'verbose_name': 'séance',
                'ordering': ['-date', 'groupe'],
            },
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('type', models.CharField(choices=[('titre', 'Titre / couverture'), ('section', 'Intro de module'), ('contenu', 'Contenu'), ('chiffre', 'Chiffre clé'), ('activite', 'Activité'), ('quiz', 'Lancement de quiz'), ('atelier', 'Atelier emails (interactif)'), ('scenario', "Scénario d'incident (interactif)")], default='contenu', max_length=20)),
                ('surtitre', models.CharField(blank=True, max_length=200)),
                ('titre', models.CharField(max_length=250)),
                ('corps', models.TextField(blank=True, help_text='HTML simple. Jetons : {entreprise} {domaine} {contact_it} {signalement} {formateur} {date}')),
                ('notes', models.TextField(blank=True, verbose_name='Notes du formateur')),
                ('quiz_moment', models.CharField(blank=True, choices=[('entree', 'Entrée'), ('sortie', 'Sortie')], max_length=10)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='sensibilisation.module')),
            ],
            options={
                'ordering': ['module__ordre', 'ordre'],
            },
        ),
        migrations.CreateModel(
            name='ReponseQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moment', models.CharField(choices=[('entree', 'Entrée'), ('sortie', 'Sortie')], max_length=10)),
                ('jeton_participant', models.CharField(max_length=40)),
                ('reponses', models.JSONField(default=dict, help_text='{question_id: choix_id}')),
                ('score', models.PositiveIntegerField(default=0)),
                ('total', models.PositiveIntegerField(default=0)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('seance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses_quiz', to='sensibilisation.seance')),
            ],
            options={
                'verbose_name': 'réponse au quiz',
                'verbose_name_plural': 'réponses au quiz',
                'unique_together': {('seance', 'moment', 'jeton_participant')},
            },
        ),
        migrations.CreateModel(
            name='ReponseAtelier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jeton_participant', models.CharField(max_length=40)),
                ('pense_piege', models.BooleanField(verbose_name='A signalé comme piégé')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='sensibilisation.emailexercice')),
                ('seance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses_atelier', to='sensibilisation.seance')),
            ],
            options={
                'verbose_name': "réponse à l'atelier",
                'verbose_name_plural': "réponses à l'atelier",
                'unique_together': {('seance', 'email', 'jeton_participant')},
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jeton_participant', models.CharField(max_length=40)),
                ('notes', models.JSONField(default=dict)),
                ('retient', models.TextField(blank=True, verbose_name='Ce que je retiens')),
                ('ameliorer', models.TextField(blank=True, verbose_name='À améliorer')),
                ('approfondir', models.TextField(blank=True, verbose_name='À approfondir')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('seance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='sensibilisation.seance')),
            ],
            options={
                'unique_together': {('seance', 'jeton_participant')},
            },
        ),
    ]
