# Generated by Django 5.2.17 on 2026-09-26 05:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensibilisation', '0003_live_campagne_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='video_fichier',
            field=models.FileField(blank=True, help_text='Lue sans Internet, prioritaire sur YouTube. Formats : MP4 ou WebM.', upload_to='videos/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'webm'])], verbose_name='Vidéo locale (MP4)'),
        ),
    ]
