# Generated by Django 5.2.17 on 2026-09-27 02:06

import django.db.models.deletion
import sensibilisation.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensibilisation', '0004_video_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campagne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Ex. : Back-office — septembre', max_length=150)),
                ('expediteur_affiche', models.CharField(blank=True, help_text='Nom et adresse montrés au destinataire. Vide = ceux du modèle.', max_length=200, verbose_name='Expéditeur affiché')),
                ('autorise_par', models.CharField(blank=True, help_text='Nom et fonction du responsable client (DG, RSSI) qui autorise la campagne.', max_length=200, verbose_name='Autorisée par')),
                ('date_autorisation', models.DateField(blank=True, null=True, verbose_name="Date d'autorisation")),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('prete', 'Prête à lancer'), ('lancee', 'Lancée'), ('terminee', 'Terminée')], default='brouillon', max_length=12)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('lance_le', models.DateTimeField(blank=True, null=True)),
                ('modele', models.ForeignKey(help_text="Le modèle d'email envoyé (bibliothèque du pack).", on_delete=django.db.models.deletion.PROTECT, related_name='campagnes', to='sensibilisation.emailexercice')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campagnes', to='sensibilisation.organisation')),
            ],
            options={
                'verbose_name': 'campagne de simulation',
                'verbose_name_plural': 'campagnes de simulation',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='DestinataireCampagne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('nom', models.CharField(blank=True, max_length=120)),
                ('service', models.CharField(blank=True, max_length=120)),
                ('jeton', models.CharField(default=sensibilisation.models.generer_jeton, editable=False, max_length=64, unique=True)),
                ('envoye_le', models.DateTimeField(blank=True, null=True)),
                ('ouvert_le', models.DateTimeField(blank=True, null=True)),
                ('clique_le', models.DateTimeField(blank=True, null=True)),
                ('donnees_saisies', models.BooleanField(default=False, verbose_name='A saisi des données sur la fausse page')),
                ('a_signale', models.BooleanField(default=False, verbose_name="A signalé l'email")),
                ('a_lu_lecon', models.BooleanField(default=False)),
                ('campagne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinataires', to='sensibilisation.campagne')),
            ],
            options={
                'verbose_name': 'destinataire de campagne',
                'verbose_name_plural': 'destinataires de campagne',
                'ordering': ['service', 'email'],
                'unique_together': {('campagne', 'email')},
            },
        ),
    ]
