# Generated by Django 5.2.17 on 2026-10-02 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensibilisation', '0005_campagnes'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailexercice',
            name='bibliotheque',
            field=models.BooleanField(default=True, help_text='Affiché dans la liste des emails de simulation. Décoché pour les emails créés pour une campagne précise.', verbose_name='Dans la bibliothèque'),
        ),
    ]
