"""Bibliothèque de modèles d'emails ancrés au Sénégal (esprit Kaspersky Kasap).

Tous les expéditeurs, domaines et liens sont fictifs. Les modèles ne font pas
partie du pack par défaut (actif=False) : le formateur les coche pour une
séance dans « Modifier la séance ».
"""

MODELES_LOCAUX = [
    {
        "categorie": "mobile money",
        "expediteur_nom": "Orange Money",
        "expediteur_adresse": "service-client@orange-money-sn.info",
        "objet": "Votre compte Orange Money est suspendu",
        "corps": "Cher client,\n\nSuite à une activité inhabituelle, votre compte Orange Money a été suspendu. Pour le réactiver, confirmez votre numéro et votre code secret dans les 12 heures.\n\nService client Orange Money",
        "url_affichee": "http://orange-money-sn.info/reactivation",
        "piege": True,
        "indices": "Domaine .info qui imite l'opérateur\nDemande du code secret : aucun opérateur ne le demande\nDélai court (12 heures) pour vous presser",
        "page_lecon": "<p>Orange Money, Wave ou Free Money ne vous demandent <strong>jamais</strong> votre code secret, ni par email, ni par SMS, ni au téléphone.</p><p>Un compte réellement bloqué se règle en agence ou via l'application officielle, jamais via un lien reçu.</p>",
    },
    {
        "categorie": "mobile money",
        "expediteur_nom": "Wave Sénégal",
        "expediteur_adresse": "notification@wave-transfert.com",
        "objet": "Vous avez reçu 75 000 F — confirmez le transfert",
        "corps": "Bonjour,\n\nUn transfert de 75 000 F est en attente sur votre compte. Pour le recevoir, confirmez votre identité avec votre numéro Wave et le code reçu par SMS.\n\nL'équipe Wave",
        "url_affichee": "http://wave-transfert.com/recevoir",
        "piege": True,
        "indices": "Argent inattendu : l'appât classique\nOn ne « confirme » jamais la réception d'un transfert\nLe code SMS sert à prendre le contrôle du compte",
        "page_lecon": "<p>Recevoir de l'argent ne demande <strong>aucune action</strong> : le montant arrive seul sur le compte.</p><p>Le code reçu par SMS est la clé de votre compte. Le donner, c'est laisser l'escroc vider le solde.</p>",
    },
    {
        "categorie": "opérateur",
        "expediteur_nom": "Orange Business Sénégal",
        "expediteur_adresse": "facturation@orange-sn-pro.com",
        "objet": "Facture impayée — coupure de vos lignes sous 48 h",
        "corps": "Madame, Monsieur,\n\nSauf erreur de notre part, la facture de vos lignes professionnelles reste impayée. Sans régularisation sous 48 h, les lignes de {entreprise} seront suspendues.\n\nRéglez en ligne par carte bancaire.",
        "url_affichee": "http://orange-sn-pro.com/paiement",
        "piege": True,
        "indices": "Menace de coupure pour créer la panique\nPaiement par carte via un lien\nDomaine qui n'est pas celui de l'opérateur",
        "page_lecon": "<p>Les factures professionnelles passent par le service achats ou comptabilité de {entreprise}, pas par un lien de paiement reçu par email.</p><p>Réflexe : transférer à la comptabilité et à {signalement}.</p>",
    },
    {
        "categorie": "colis",
        "expediteur_nom": "DHL Express Dakar",
        "expediteur_adresse": "dakar@dhl-livraisons.net",
        "objet": "Colis en attente de dédouanement — 4 500 F à régler",
        "corps": "Bonjour,\n\nVotre colis est bloqué au dépôt de Dakar. Des frais de dédouanement de 4 500 F sont à régler avant demain 16h, sinon le colis sera retourné à l'expéditeur.",
        "url_affichee": "http://dhl-livraisons.net/dakar/paiement",
        "piege": True,
        "indices": "Colis que vous n'attendez pas\nPetite somme + délai court\nDomaine .net sans lien avec le transporteur",
        "page_lecon": "<p>La petite somme sert à récupérer <strong>votre numéro de carte</strong>, qui sera ensuite débité bien plus.</p><p>Suivez un colis uniquement depuis le site officiel du transporteur, en tapant l'adresse vous-même.</p>",
    },
    {
        "categorie": "administration",
        "expediteur_nom": "DGID — Impôts et Domaines",
        "expediteur_adresse": "remboursement@dgid-gouv-sn.org",
        "objet": "Remboursement d'impôt de 128 000 F en attente",
        "corps": "Bonjour,\n\nAprès vérification, vous bénéficiez d'un remboursement de 128 000 F. Complétez vos coordonnées bancaires pour recevoir le virement sous 72 h.",
        "url_affichee": "http://dgid-gouv-sn.org/remboursement",
        "piege": True,
        "indices": "Une administration n'écrit pas depuis un domaine .org imitant .gouv.sn\nArgent promis contre coordonnées bancaires\nAucune référence de dossier",
        "page_lecon": "<p>L'administration fiscale ne demande jamais vos coordonnées bancaires par email pour un remboursement.</p><p>En cas de doute, passez par le site officiel ou votre centre des impôts, jamais par le lien reçu.</p>",
    },
    {
        "categorie": "compte",
        "expediteur_nom": "Administrateur messagerie",
        "expediteur_adresse": "admin@{domaine}.mail-verify.co",
        "objet": "Votre messagerie {entreprise} sera bloquée ce soir",
        "corps": "Bonjour,\n\nVotre boîte a atteint sa limite de stockage. Elle sera bloquée ce soir à 18h. Validez votre compte pour conserver vos emails.\n\nAdministrateur système",
        "url_affichee": "http://{domaine}.mail-verify.co/login",
        "piege": True,
        "indices": "Le domaine se termine par mail-verify.co, pas par {domaine}\nMenace de blocage le jour même\nPage de connexion hors de l'entreprise",
        "page_lecon": "<p>Lisez un domaine <strong>de droite à gauche</strong> : <em>{domaine}.mail-verify.co</em> appartient à mail-verify.co, pas à {entreprise}.</p><p>L'informatique interne ({contact_it}) ne demande jamais votre mot de passe.</p>",
    },
    {
        "categorie": "cloud",
        "expediteur_nom": "OneDrive",
        "expediteur_adresse": "partage@sharepoint-docs.net",
        "objet": "Document partagé avec vous : Primes_2026.xlsx",
        "corps": "Un collègue a partagé un fichier avec vous.\n\nPrimes_2026.xlsx\n\nOuvrez le document avec votre compte professionnel.",
        "url_affichee": "http://sharepoint-docs.net/view/Primes_2026",
        "piege": True,
        "indices": "Nom du collègue absent\nSujet sensible (primes) pour attiser la curiosité\nDemande de connexion hors du domaine Microsoft officiel",
        "page_lecon": "<p>Le faux partage de document est le modèle le plus cliqué dans les campagnes de simulation.</p><p>Un vrai partage vient d'un collègue identifiable : en cas de doute, demandez-lui directement.</p>",
    },
    {
        "categorie": "rh",
        "expediteur_nom": "Ressources humaines",
        "expediteur_adresse": "rh@{domaine}",
        "objet": "Votre bulletin de paie est disponible sur l'intranet",
        "corps": "Bonjour,\n\nVotre bulletin de paie du mois est disponible dans votre espace RH, sur l'intranet habituel. Aucune information ne vous est demandée par email.\n\nLe service RH",
        "url_affichee": "https://intranet.{domaine}/rh/paie",
        "piege": False,
        "indices": "Expéditeur au domaine interne {domaine}\nLien vers l'intranet habituel\nAucune donnée demandée",
        "page_lecon": "",
    },
    {
        "categorie": "interne",
        "expediteur_nom": "Agenda d'équipe",
        "expediteur_adresse": "agenda@{domaine}",
        "objet": "Invitation : réunion d'équipe lundi 9h",
        "corps": "Bonjour,\n\nRéunion d'équipe lundi à 9h, salle habituelle. Ordre du jour : planning du mois.\n\nMerci de confirmer dans votre agenda.",
        "url_affichee": "",
        "piege": False,
        "indices": "Domaine interne\nContexte attendu\nAucune pièce jointe ni lien externe",
        "page_lecon": "",
    },
]
